### PR TITLE
fix(MessageIterator): copy the result array before resolving it

### LINKED ISSUE #240: result.value.reverse() 会使 realtime 里定义的 forEach 失效
https://forum.leancloud.cn/t/messageiterator/8747

### PR DESCRIPTION
**Pull request by leeyeh**
fix #240

### CODE REVIEW

File: test/conversation.js [hunk 1]
```diff
@@ -174,20 +174,36 @@ describe('Conversation', () => {
...
+          limit: 2,
+        });
+        return Promise.all([iterator.next(), iterator.next()])
+          .then(([page1, page2]) => {
+            page1.value.should.be.an.Array();
+            page1.done.should.eql(false);
+            page2.value.should.be.an.Array();
+            const minMessageTimestamp =
+              Math.min(page1.value[0].timestamp, page1.value[1].timestamp);
+            page2.value[0].timestamp.should.lessThan(minMessageTimestamp);
```
Comment (wangxiao) [inline test/conversation.js]: 用例中好像没有对长度的检测，should.eql(2)
